### ISSUE TITLE
Hardfault in lfs_remove / lfs_dir_remove

### ISSUE THREAD

**Issue by apullin** [ARMmbed/littlefs#60]
I am hitting a hardfault inside lfs_paircmp, from lfs_dir_remove, from lfs_remove, specifically on line 734.

How can I go about debugging the root cause here? The two obvious causes are either an incorrect implementation of the driver by myself, or an incorrect usage of lfs_remove.

**Comment by geky** [comment]
That's unfortunate. Which commit hash are you using? I'm guessing this is line 731 on master.

Looking at that line, I'm surprised your getting a hard fault. The `f` pointer can't be NULL because of the for loop, and if `dir` was NULL, the function would have hard faulted much earlier.

---

My guess is the littlefs linked-list of files is getting corrupted. littlefs keeps a linked list of any open files so it can update files if the filesystem changes state.

Do you make sure to call `lfs_file_close` on all of your files? Are any files getting deallocated before `lfs_file_close`?

Unfortunately, this could also be caused by a buffer overflow. What is the value of `f` when it hard faults? The bytes may look like data from another buffer. If you have a debugger and your device supports watch points, maybe setting a watch point on the memory location of `f` could find out who set it to an invalid value.

A stack overflow could also corrupt `f`. Do you have a way to catch stack overflows? Unfortunately debugging stack overflows is rather platform specific.

If you have a dump of the disk image, I could try reproducing it locally and see if littlefs is entering a bad state. Though I suspect this sort of bug will be specific to the platform.

**Comment by apullin** [comment]
There is a fair chance that I am not closing files completely or correctly.
This is all inside an rsync-like function, that has to check for existence, check for length and delete if mismatched, attempt download but delete the file if download is incomplete (including possibly a 0-length file), and then also check MD5 of the file after the fact.
I may simply be using the lfs library incorrectly. I will post the example code shortly.

All other tests are possible, too, and I will report on those shortly.

What are ways for a file to deallocate before `lfs_file_close`?

**Comment by geky** [comment]
Ah, that sounds like it may be the problem. There's currently no way to "cancel" a modified file. Maybe it would be useful to add a "lfs_file_cancel" function?

The usual pattern for atomically updating files on a POSIX file system is to download as a temporary file, and then rename the temporary file to your destination. This rename will be atomic, and you can delete the temporary file when needed. Though this does add complexity in your case.

**Comment by apullin** [comment]
I do not yet understand enough about the underlying implementation or about filesystem fundamentals to know how to write a lfs_file_cancel function, unfortunately. I am not even sure what is implied by "cancel" and "modified" in this situation.

Does this have to do with sync'ing changes? My implementation for the sync function is empty, as all the other read/write functions are immediate, blocking transactions with the serial flash chip.

**Comment by geky** [comment]
Ah, sorry @apullin. The issue isn't with transaction to the serial flash chip. The issue is with littlefs's internal state (in RAM). When you open and write a file, the state of RAM and state of disk go out of sync until you call lfs_file_close. A call to lfs_file_close (or lfs_file_sync) commits your changes to the disk, putting the RAM and disk in sync again.

This state is actually stored in the `lfs_file_t` struct that you provide, and it is connected to the rest of littlefs with some linked-lists. Calling lfs_file_close is required before deallocating a `lfs_file_t` or the state in RAM will become corrupted.

There is currently no way to deallocate a `lfs_file_t` without calling close. This is because littlefs is based on the standard POSIX API, which doesn't have an understanding of the difference between RAM and disk. We could easily add a function to add this feature (I was thinking `lfs_file_cancel`, since it effectively "cancels" a open-write-close operation). Note, code written to use `lfs_file_cancel` would not be portable to other filesystem, if you care about that.

Note, with all of this, RAM is destroyed on power-loss, so there's nothing that could be corrupted in that situation.

I hope that explains the technical stuff a bit more, let me know any questions you have.

---

Right now, (and if you want to use portable POSIX APIs), the correct way to perform this sort of cancelable file download would be to write to a temporary file.

Here's an example of what this would look like (pardon my terrible pseudocode):
``` c
lfs_t lfs;
lfs_file_t temp;
int start_download(void) {
    int err = lfs_file_open(&lfs, &temp, "data-temp", LFS_O_WRONLY | LFS_O_TRUNC | LFS_O_CREAT);
    if (err) {
        return err;
    }

    return 0;
}

int download_chunk(uint8_t *buffer, lfs_size_t size) {
    int err = lfs_file_write(&lfs, &temp, buffer, size);
    if (err < 0) {
        return err;
    }
}

int finish_download(void) {
    // close file, then we can deallocate temp
    int err = lfs_file_close(&lfs, &temp);
    if (err) {
        return err;
    }

    // make the downloaded file active
    err = lfs_file_rename(&lfs, "data-temp", "data");
    if (err) {
        return err;
    }

    return 0;
}

int cancel_download(void) {
    // we still need to close the file calmly before we can deallocate the file
    int err = lfs_file_close(&lfs, &temp);
    if (err) {
        return err;
    }

    // we don't need to call rename, because "data-temp" contains a half-downloaded file,
    // we _could_ delete "data-temp", but it will be deleted on the next download (with the
    // O_TRUNC flag), so there's no need to do extra work here
    return 0;
}
```

**Comment by apullin** [comment]
FWIW, this issue seems to be resolved in the fix_memory_leaks branch that a PR is up for.

If I want to check if a file already exists, what is the best/correct way?
Presently, I am doing:

```
    // Start file
    err = lfs_file_open(&lfs, &file, filename, LFS_O_RDWR | LFS_O_CREAT | LFS_O_EXCL);

    if (err < 0)
    {
        log("File %s already exists, deleting ... ", filename);
        err = lfs_remove(&lfs, filename);
        log("... done (%d)\n", err);
        err = lfs_file_open(&lfs, &file, filename, LFS_O_RDWR | LFS_O_CREAT | LFS_O_EXCL);
    }
```

Then if an error occurs during download, I try to delete it with:
```
    err = lfs_file_close( &lfs, &file );
    //If the file was partially written, delete it
    {   struct lfs_info info;
        err = lfs_stat( &lfs, filename, &info );
        if( (err < 0) || (info.size > 0) ){
            err = lfs_remove(&lfs, filename); //delete file
        }
    }
```

Then, later, I check the file length, I do:
```
    struct lfs_info info;
    err = lfs_stat(&lfs, this_record->path, &info);
    if( info.size != (uint32_t)(this_record->file_length) ){
            log("Sync, lenght mismatch for %s, have=%lu, expect=%lu\n",
                                            this_record->path, info.size, this_record->file_length);
            err = lfs_file_close(&lfs, &file);
            storman_log_msg(WICED_LOG_INFO, "Removing %s\n", this_record->path);
            err = lfs_remove(&lfs, this_record->path);
            continue; // go back around and attemp open/download cycle
        }
```

And lastly, I check the MD5 versus an expected MD5:
```
        result = file_md5(this_record->path, md5_have); //stores into md5_have
        if(memcmp(md5_have, this_record->md5, sizeof(md5_have)) != 0){
            char md5_str[33];
            log( "Sync, MD5 mismatch for %s\n", this_record->path );
            md5_to_string(md5_have, md5_str);
            log( "Have md5(%s) = %s\n", this_record->path, md5_str );
            md5_to_string((uint8_t*)(this_record->md5), md5_str);
            log( "Need md5(%s) = %s\n", this_record->path, md5_str );

            err = lfs_file_close(&lfs, &file);
            log( "Removing %s\n", this_record->path );
            err = lfs_remove(&lfs, this_record->path);
            continue; // go back around and attemp open/download cycle
        }
```

There are a few thing that I am still not sure about, and so I am likely missing some basic safety stuff in there. 
For example: is it safe to call lfs_file_close if the file is already closed? Or, is there a way to test if an lfs_file struct is presently representing an open file?

**Comment by geky** [comment]
That's good to hear, sorry it was giving you so much problems.

> is it safe to call lfs_file_close if the file is already closed?

It's not safe to call lfs_file_close multiple times. Looking at your code I don't think you need to keep the file open after an error during download? Can you handle both the error and and normal exit in the same code path and call lfs_file_close there? Otherwise you will need to set a "file open" flag to avoid closing the file multiple times.

There's currently no function for testing if a struct is open, since uninitialized memory could look like an open file. Though it's relatively easy to track that state with a flag if needed.

> If I want to check if a file already exists, what is the best/correct way?

Your current implementation looks like it should work perfectly fine as far as I can tell.

One tip that may help, generally with posix apis, it's better to try and ask for forgiveness. In your case you can try the remove, which will have no side effects if it can't find the file:

``` c
// Remove the file if it exists
err = lfs_remove(&lfs, filename);
if (err < 0 && err != LFS_ERR_NOENT) {
    return err;
}

// Start file
err = lfs_file_open(&lfs, &file, filename, LFS_O_RDWR | LFS_O_CREAT | LFS_O_EXCL);
if (err < 0)
{
    return err;
}
```

You can do the same when you have a download error

``` c
err = lfs_file_close( &lfs, &file );
// If the file was partially written, delete it, ignore missing files
if (err < 0) {
    err = lfs_remove(&lfs, filename);
    if (err < 0 && err != LFS_ERR_NOENT) {
        return err;
    }
}
```

**Comment by geky** [comment]
Ah, glad you were able to find it.

> Are multiple open's of the file acceptable? As in, if have the file open in the parent, but then I have a self-contained operation in file_md5() where I open,hash,close the file, is that an incorrect usage?

That should work just fine. Though keep in mind littlefs files are COW, that is, when you write to a file, the changes aren't visible until you close or manually sync the file.

So you may need to do something like this:
``` c
lfs_file_open(f, "filename");
// write stuff to file
lfs_file_sync(f); // make changes visible
file_md5("filename"); // opens file in this function
// more things to f
lfs_file_close(f); // still needed to free up memory
```

**Comment by apullin** [comment]
Sync is not an issue in my implementation since all the flash operations are immediate inside the read/write/erase function.
Doing it any other way would be way too complex! I suppose I could delegate single operations, and then have sync() just check for a done a done/ready flag, but it seems to work fairly well without that.
